name: Validacion de mi Proyecto
on: [push] # Se activa cada vez que haces push

jobs:
  ejecutar-pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar mi archivo de prueba
        run: node tets.js